[versions]
agp = "8.13.2"
kotlin = "2.3.21"
kotlinx-serialization = "1.11.0"
r8-annotations = "v1.0.1"
sun-cleaner = "v1.0.1"
panama = "c0d8fa4"
zygoteloader = "bf5078e182"

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
agp-lib = { id = "com.android.library", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
zygoteloader = { id = "com.github.aerath-stuff.ZygoteLoader", version.ref = "zygoteloader" }

[libraries]
androidx-annotation-jvm = { module = "androidx.annotation:annotation-jvm", version = "1.10.0" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
r8annotations = { module = "io.github.vova7878:R8Annotations", version.ref = "r8-annotations" }
sun-cleaner = { module = "io.github.vova7878:SunCleanerStub", version.ref = "sun-cleaner" }
panama-core = { module = "com.github.aerath-stuff.PanamaPort:Core", version.ref = "panama" }
panama-unsafe = { module = "com.github.aerath-stuff.PanamaPort:Unsafe", version.ref = "panama" }
panama-llvm = { module = "com.github.aerath-stuff.PanamaPort:LLVM", version.ref = "panama" }